package org.mojoz

import org.mojoz.metadata.ViewDef
import org.mojoz.metadata.in.YamlMd
import org.mojoz.querease.{Querease, QuereaseMetadata}
import org.mojoz.querease.compiling.ViewCompiler
import sbt.Def.Classpath
import sbt.Keys.{fileConverter, streams, *}
import sbt.plugins.JvmPlugin
import sbt.{AutoPlugin, Compile, Def, File, config, settingKey, taskKey}
import sbtcompat.PluginCompat._

object MojozPlugin extends AutoPlugin {
  object autoImport {
    val mojozResourceClassLoaderFiles = taskKey[Seq[File]]("Files for classLoader for resource loading for compilation")
    val mojozDtosPackage = settingKey[String]("Package where all dtos should be placed in")
    val mojozDtosImports = settingKey[Seq[String]]("List of imports for Dtos.scala")

    val mojozJobMetadataFolders = settingKey[Seq[File]]("Job metadata folders for wabase projects")
    val mojozJobMetadataFiles = taskKey[Seq[(File, String)]]("All job metadata files + relative paths they are kept in")

    val mojozRouteMetadataFolders = settingKey[Seq[File]]("Route metadata folders for wabase projects")
    val mojozRouteMetadataFiles = taskKey[Seq[(File, String)]]("All route metadata files + relative paths they are kept in")

    val mojozViewMetadataFolders = settingKey[Seq[File]]("Mojoz view metadata folders")
    val mojozViewMetadataFiles = taskKey[Seq[(File, String)]]("All view metadata files + relative paths they are kept in")

    val mojozMetadataFilesForResources = taskKey[Seq[(File, String)]]("All metadata files to be copied to resources and included in -md-files.txt")
    val mojozMdFilesFileName = settingKey[String]("File name for metadata filename list of all table and view files, defaults to \"-md-files.txt\"")
    val mojozShouldGenerateMdFileList = settingKey[Boolean]("Should -md-files.txt be generated, defaults to true")
    val mojozGenerateMdFileList = taskKey[Seq[File]]("Generates -md-files.txt")

    val mojozRawJobMetadata  = taskKey[Seq[YamlMd]]("Raw job metadata")
    val mojozRawRouteMetadata= taskKey[Seq[YamlMd]]("Raw route metadata")
    val mojozRawViewMetadata = taskKey[Seq[YamlMd]]("Raw view metadata")
    val mojozRawYamlMetadata = taskKey[collection.immutable.Seq[YamlMd]]("Raw yaml metadata - job metadata and view metadata")

    val mojozViewMetadata = taskKey[List[ViewDef]]("View metadata")
    val mojozShouldCompileViews = settingKey[Boolean]("Should views be compiled, defaults to true")
    val mojozShowFailedViewQuery = settingKey[Boolean]("Show query string if view fails to compile, defaults to false")
    val mojozCompileViews = taskKey[Seq[File]]("View compilation task. Returns view compiler cache files")
    val mojozResourceGenerators = taskKey[Seq[File]]("All mojoz resource generation tasks")
    val mojozSourceGenerators = taskKey[Seq[File]]("All mojoz source generation tasks")
    val mojozAllSourceFiles = taskKey[Seq[File]]("All mojoz source files - for source watch and view compilation")
    val mojozAllCompilerMetadataFiles = taskKey[Seq[File]]("All compiler metadata files - for mojozCompileViews cache invalidation. Customize if mojozTresqlMacrosClass is customized")
    val mojozTresqlMacrosClass = taskKey[Option[Class[?]]] ("Macros class for view compilation. Defaults to org.mojoz.querease.QuereaseMacros. Customization rarely needed - use tresql-macros.txt instead")
    val mojozQuerease = taskKey[Querease & ViewCompiler]("Creates an instance of Querease for view compilation etc.")
    val mojozGenerateDtosScalaFileName = settingKey[String]("File name where dtos are stored, default  Dtos.scala")
    val mojozGenerateDtosViewMetadata = taskKey[List[ViewDef]]("View metadata for dtos generation")
    val mojozGenerateDtosMappingsViewMetadata = taskKey[List[ViewDef]]("View metadata for dtos mappings generation")
    val mojozShouldGenerateDtos = taskKey[Boolean]("Should DTO-s be generated, defaults to true")
    val mojozGenerateDtosScala = taskKey[Option[File]]("Generates Dtos.scala")
    val mojozGenerateDtosMappingsScala = taskKey[String]("Generates extras (name to class mappings etc.) for Dtos.scala")
    val mojozGeneratedFiles = taskKey[Seq[String]]("Lists files generated by MojozPlugin")
    val mojozScalaGenerator = taskKey[org.mojoz.metadata.out.ScalaGenerator]("Creates scala (i.e. Dtos) generator")
    val mojozUninheritableExtras = settingKey[collection.immutable.Seq[String]]("View extensions not to be inherited")
    val mojozCompilerResourceFiles = taskKey[Seq[File]]("Unmanaged and managed resource files required on compile classpath")
    val mojozBeforeCompile = taskKey[File]("Copies compiler resources to classDirectory and creates or copies tresql-scala-macro.properties before compile")

    lazy val MojozMacroCompile = config("macro-compile").extend(Compile)
    lazy val mojozMacroSources = taskKey[Seq[File]]("Macro source files")
    val mojozMacroCompile = taskKey[Unit]("Compiles Scala macro sources using the SBT's scala compiler as a Java subprocess and project's scalaVersion Scala compiler")
    val sbtClassDirectory = taskKey[File]("SBT's directory of compiled classes, i.e. project/target/...")
  }

  import MojozTableMetadataPlugin.autoImport.*
  import autoImport.*
  override def trigger = noTrigger
  override def requires = JvmPlugin && MojozTableMetadataPlugin

  import sbt.*
  import sbt.util.FileInfo

  override val projectSettings: Seq[Def.Setting[?]] = Seq(

    mojozResourceClassLoaderFiles := Def.uncached(
      (Compile / resourceDirectories).value ++ Seq((MojozMacroCompile / sbtClassDirectory).value)
    ),

    mojozDtosPackage := "dto",
    mojozDtosImports := Seq(
      "org.mojoz.querease.QuereaseMetadata", // used in resolver parameters
      "org.tresql._",
    ),

    mojozJobMetadataFolders := Seq(baseDirectory.value / "jobs"),
    mojozJobMetadataFiles := Def.uncached { mojozJobMetadataFolders.value.flatMap { mojozJobMetadataFolder =>
      Path.selectSubpaths(mojozJobMetadataFolder, _.isFile).map {
        case (f, p) => (f, mojozJobMetadataFolder.getName + "/" + p.replace('\\', '/'))
      }.filter(f => mojozMetadataFileFilterPredicate.value(f._1))
    }},

    mojozRouteMetadataFolders := Seq(baseDirectory.value / "routes"),
    mojozRouteMetadataFiles := Def.uncached { mojozRouteMetadataFolders.value.flatMap { mojozRouteMetadataFolder =>
      Path.selectSubpaths(mojozRouteMetadataFolder, _.isFile).map {
        case (f, p) => (f, mojozRouteMetadataFolder.getName + "/" + p.replace('\\', '/'))
      }.filter(f => mojozMetadataFileFilterPredicate.value(f._1))
    }},

    mojozViewMetadataFolders := Seq(baseDirectory.value / "views"),
    mojozViewMetadataFiles := Def.uncached { mojozViewMetadataFolders.value.flatMap { mojozViewMetadataFolder =>
      Path.selectSubpaths(mojozViewMetadataFolder, _.isFile).map {
        case (f, p) => (f, mojozViewMetadataFolder.getName + "/" + p.replace('\\', '/'))
      }.filter(f => mojozMetadataFileFilterPredicate.value(f._1))
    }},

    mojozMetadataFilesForResources := Def.uncached(
      mojozJobMetadataFiles.value   ++
      mojozRouteMetadataFiles.value ++
      mojozTableMetadataFiles.value ++
      mojozViewMetadataFiles.value),

    mojozMdFilesFileName := ((Compile / resourceManaged).value / "-md-files.txt").getAbsolutePath,

    mojozShouldGenerateMdFileList := true,
    mojozGenerateMdFileList := Def.uncached {
      if(mojozShouldGenerateMdFileList.value) {
        val file = new File(mojozMdFilesFileName.value)
        val contents = mojozMetadataFilesForResources.value.map(_._2).toSet.toSeq.sorted.mkString("", "\n", "\n")
        IO.write(file, contents)
        Seq(file)
      } else Seq()
    },

    mojozResourceGenerators := Def.uncached(
      mojozCompileViews.value ++
      mojozGenerateMdFileList.value),

    mojozRawJobMetadata := Def.uncached(mojozJobMetadataFiles.value.map(_._1).flatMap(YamlMd.fromFile)),

    mojozRawRouteMetadata := Def.uncached(mojozRouteMetadataFiles.value.map(_._1).flatMap(YamlMd.fromFile)),

    mojozRawViewMetadata := Def.uncached(mojozViewMetadataFiles.value.map(_._1).flatMap(YamlMd.fromFile)),

    mojozRawYamlMetadata := Def.uncached(
      (mojozRawJobMetadata.value ++ mojozRawRouteMetadata.value ++ mojozRawViewMetadata.value).toVector),

    mojozViewMetadata := Def.uncached(mojozQuerease.value.viewDefLoader.plainViewDefs),
    mojozGenerateDtosViewMetadata := Def.uncached(mojozViewMetadata.value),
    mojozGenerateDtosMappingsViewMetadata := Def.uncached(mojozViewMetadata.value),

    mojozTresqlMacrosClass := Def.uncached {
      val _ = (MojozMacroCompile / mojozMacroCompile).value
      Option(QuereaseMetadata.resolveMacrosClass(MojozPlugin.getMojozResourceClassLoader(mojozResourceClassLoaderFiles.value)))
    },
    mojozShouldCompileViews := true,
    mojozShowFailedViewQuery := false,
    mojozQuerease := Def.uncached(
      new Querease with ViewCompiler {
        override lazy val aliasToDb           = mojozDbAliasToDb.value
        override lazy val yamlMetadata        = mojozRawYamlMetadata.value
        override lazy val metadataConventions = mojozMdConventions.value
        override lazy val typeDefs            = mojozTypeDefs.value
        override lazy val tableMetadata       = mojozTableMetadata.value
        override lazy val macrosClass         = mojozTresqlMacrosClass.value.orNull
        override lazy val resourceClassLoader = MojozPlugin.getMojozResourceClassLoader(mojozResourceClassLoaderFiles.value)
        override lazy val uninheritableExtras = mojozUninheritableExtras.value
        override protected lazy val parserCacheSize = -1 // unlimited cache for compilation
      }),
    mojozAllCompilerMetadataFiles := Def.uncached {
      Seq(
        ((Compile / unmanagedResources).value ** "*-patterns.txt").get(),
        mojozCustomTypesFile.value.toSeq,
        mojozTableMetadataFiles.value.map(_._1),
        ((Compile / unmanagedResources).value ** "reference.conf").get(),
        ((Compile / unmanagedResources).value ** "tresql-function-signatures*.txt").get(),
        ((Compile / unmanagedResources).value ** "tresql-macros.txt").get(),
        ((Compile / unmanagedResources).value ** "tresql-resources.conf").get(),
        ((Compile / unmanagedResources).value ** "tresql-scala-macro.properties").get(),
        Seq((MojozMacroCompile / sbtClassDirectory).value / ".mojoz-macro-compile-stamp"),
      ).flatten
    },
    mojozAllSourceFiles := Def.uncached(
      mojozAllCompilerMetadataFiles.value ++
      mojozJobMetadataFiles.value.map(_._1) ++
      mojozRouteMetadataFiles.value.map(_._1) ++
      mojozViewMetadataFiles.value.map(_._1)),
    mojozCompileViews := Def.uncached {
      var compilerCacheFileNames: Seq[String] = Nil
      val mojozCompilerCacheFolder = (Compile / resourceManaged).value
      def compileViews(previouslyCompiledQueries: Set[String] = Set.empty): Set[String] = {
        val (compiledViews, caches) =
         try {
          mojozQuerease.value.compileAllQueries(
            previouslyCompiledQueries,
            mojozShowFailedViewQuery.value,
            streams.value.log.info(_),
          )
         } catch {
          case scala.util.control.NonFatal(ex) if !mojozShowFailedViewQuery.value =>
            throw new RuntimeException(
              s"${ex.getMessage}\nRunning with mojozShowFailedViewQuery := true might add more details.", ex)
         }
        compilerCacheFileNames =
          caches.map { case (name, cache) =>
            val file = mojozCompilerCacheFolder / name
            IO.write(file, cache)
            name
          }.toSeq
        compiledViews
      }
      import sbt.util.CacheImplicits.*
      val allSourceFiles = mojozAllSourceFiles.value
      val compilerMetadataFiles = mojozAllCompilerMetadataFiles.value

      lazy val compiledQueriesCacheStore  = streams.value.cacheStoreFactory.make("mojoz-compiled-queries")
      lazy val cachedCompileViewsQ        = Tracked.lastOutput[Boolean, Set[String]](compiledQueriesCacheStore) {
        case (_, None) /* no previous output */        => compileViews()
        case (true, _) /* compiler metadata changed */ => compileViews()
        case (_, Some(previouslyCompiledQueries))      => compileViews(previouslyCompiledQueries)
      }

      lazy val compilerMetadataCacheStore = streams.value.cacheStoreFactory.make("mojoz-compiler-metadata-file-hashes")
      lazy val cachedCompileViewsM        = Tracked.inputChanged[Seq[HashFileInfo], Any](compilerMetadataCacheStore) {
        case (isCompilerMetadataChanged: Boolean, _)   => cachedCompileViewsQ(isCompilerMetadataChanged)
      }

      lazy val allSourcesCacheStore       = streams.value.cacheStoreFactory.make("mojoz-all-source-file-hashes")
      lazy val cachedCompileViews         = Tracked.inputChanged[Seq[HashFileInfo], Any](allSourcesCacheStore) {
        case (true, _)  => cachedCompileViewsM(compilerMetadataFiles.map(FileInfo.hash(_)))
        case (false, _) =>
      }

      if (mojozShouldCompileViews.value)
        cachedCompileViews(allSourceFiles.map(FileInfo.hash(_)))

      lazy val cacheFilenamesCacheStore   = streams.value.cacheStoreFactory.make("mojoz-compiler-cache-file-names")
      lazy val cachedCacheFileNames       = Tracked.lastOutput[Set[String], Set[String]](compiledQueriesCacheStore) {
        case (fileNames, previousFileNamesOpt) => fileNames ++ previousFileNamesOpt.getOrElse(Set.empty)
      }

      cachedCacheFileNames(compilerCacheFileNames.toSet)
        .toSeq.sorted
        .map(mojozCompilerCacheFolder / _)
        .filter(_.exists)
    },

    mojozScalaGenerator := Def.uncached(new org.mojoz.querease.ScalaDtoGenerator(mojozQuerease.value)),
    mojozGenerateDtosScalaFileName := "Dtos.scala",

    mojozGenerateDtosMappingsScala := Def.uncached {
      val tableMd = mojozTableMetadata.value
      val viewDefs = mojozGenerateDtosMappingsViewMetadata.value
      val classBuilder = mojozScalaGenerator.value
      val tableNames = tableMd.tableDefs.map(_.name)
      // FIXME do not search for distinct table names, change mapping structure to support multi-db tables instead?
      val distinctTableNames  = tableNames.distinct.sorted
      def scalaClassNameString(name: String) = classBuilder.scalaNameString(classBuilder.scalaClassName(name))
      val mapping = s"""
        |object Tables {
        |  ${distinctTableNames.map(t => s"class ${scalaClassNameString(t)} {}").mkString("\n  ")}
        |}
        |object DtoMapping {
        |  val viewNameToClass = Map[String, Class[? <: Dto]](
        |    ${viewDefs.map(v => s""""${v.name}" -> classOf[${scalaClassNameString(v.name)}]""").mkString(",\n    ")}
        |  )
        |  val viewClassToTableClass = Map[Class[? <: Dto], Class[?]](
        |    ${viewDefs.filter(_.table != null).map(v =>
                s"classOf[${scalaClassNameString(v.name)}] -> classOf[Tables.${scalaClassNameString(v.table)}]"
               ).mkString(",\n    ")
             }
        |  )
        |}
        |""".stripMargin.trim
      mapping
    },

    mojozShouldGenerateDtos := true,
    mojozGenerateDtosScala := Def.uncached {
      val file = (Compile / sourceManaged).value / mojozGenerateDtosScalaFileName.value
      val viewDefs = mojozGenerateDtosViewMetadata.value
      val allViewDefsMap = mojozViewMetadata.value.map(v => v.name -> v).toMap
      val classBuilder = mojozScalaGenerator.value
      val mapping = mojozGenerateDtosMappingsScala.value
      if (mojozShouldGenerateDtos.value) {
       val contents = classBuilder.generateScalaSource(
        List("package "+mojozDtosPackage.value, "") ++
          mojozDtosImports.value.map("import "+_)   ++
          List(""),
        viewDefs,
        List("", mapping),
        allViewDefsMap,
       )
       IO.write(file, contents)
       Some(file)
      } else None
    },

    mojozSourceGenerators := Def.uncached {
      mojozCompileViews.value.filter(_ => false) ++ // XXX Compile views at this point (no source generation here)
      mojozGenerateDtosScala.value.toSeq
    },

    mojozUninheritableExtras := collection.immutable.Seq("api"),

    Compile / resourceGenerators += mojozResourceGenerators.taskValue,

    Compile / sourceGenerators   += mojozSourceGenerators.taskValue,

    Compile / copyResources := Def.uncached {
      val taskStreams = streams.value
      val classDir = (Compile / classDirectory).value
      val cacheStore = streams.value.cacheStoreFactory.make("copy-resources")
      val mappings = mojozMetadataFilesForResources.value.map(f => (f._1, classDir / f._2))

      taskStreams.log.debug("result" + mappings.mkString("\n\t","\n\t",""))
      Sync.sync(cacheStore)( mappings )
      (Compile / copyResources).value ++ mappings
    },

    mojozCompilerResourceFiles := Def.uncached {
      val unmanaged = (Compile / unmanagedResources).value
      Seq(
        (unmanaged ** "*-patterns.txt").get(),
        (unmanaged ** "reference.conf").get(),
        (unmanaged ** "tresql-function-signatures*.txt").get(),
        (unmanaged ** "tresql-macros.txt").get(),
        (unmanaged ** "tresql-resources.conf").get(),
        (unmanaged ** "tresql-scala-macro.properties").get(),
        Seq(mojozGenerateTresqlTableMetadata.value),
      ).flatten.distinct
    },

    mojozBeforeCompile := Def.uncached {
      val classDir = (Compile / classDirectory).value
      val resourceDirs = (Compile / resourceDirectories).value
      val cacheStore = streams.value.cacheStoreFactory.make("mojoz-before-compile")
      val mappings = mojozCompilerResourceFiles.value.flatMap { src =>
        resourceDirs.flatMap(rd => IO.relativize(rd, src)).headOption.map(rel => (src, classDir / rel))
      }
      Sync.sync(cacheStore)(mappings)

      val dest = classDir / "tresql-scala-macro.properties"
      if (!dest.exists) {
        val macrosClassNameOpt = Option(mojozTresqlMacrosClass.value.orNull).map { c =>
          val n = c.getName
          if (n.endsWith("$")) n
          else try { c.getField("MODULE$"); n + "$" }
          catch { case _: NoSuchFieldException => n }
        }
        val lines = Seq("metadata_factory_class = org.mojoz.querease.TresqlMetadataFactory") ++
          macrosClassNameOpt.map(n => s"macros_class           = $n")
        IO.write(dest, lines.mkString("", "\n", "\n"))
      }
      dest
    },

    Compile / compile := Def.uncached {
      mojozBeforeCompile.value
      (Compile / compile).value
    },

    mojozGeneratedFiles := Def.uncached {
      val tableMd = mojozTableMetadata.value
      val viewDefs = mojozGenerateDtosViewMetadata.value
      val classBuilder = mojozScalaGenerator.value
      val packagePath = mojozDtosPackage.value.replace(".", "/")
      def classFileName(name: String) =
        // TODO classFileNameFromName
        classBuilder.scalaClassName(name)
          .replace(".", "$u002E")
      def classFilePathFromName(name: String) = packagePath + "/" + name + ".class"
      mojozResourceGenerators.value.map(_.getAbsolutePath) ++
        mojozSourceGenerators.value.map(_.getAbsolutePath) ++
        Seq("Tables$", "Tables", "DtoMapping$", "DtoMapping").map(classFilePathFromName) ++
        viewDefs.map(v => classFilePathFromName(classFileName(v.name))) ++
        tableMd.tableDefs.map(t => classFilePathFromName("Tables$" + classFileName(t.name)))
    },

    mojozMacroSources := Def.uncached {
    QuereaseMetadata.resolveMacrosClassName(getMojozResourceClassLoader((Compile / resourceDirectories).value))
     .filter(_ != null)
     .map { className =>
      try {
        Class.forName(className)
        Nil
      } catch {
        case _: ClassNotFoundException =>
          val fileName = className.split('.').last + ".scala"
          val found = (PathFinder((Compile / scalaSource).value) ** fileName).get()
          if (found.isEmpty)
            sys.error(s"Neither macro class: $className nor macro source file: $fileName found under ${(Compile / scalaSource).value.getAbsolutePath}")
          else if (found.size > 1)
            sys.error(s"Multiple source files named $fileName found:\n${found.mkString("\n")}")
          else
            found
      }
     }.getOrElse(Nil)
    },

    // sbt tilde must watch changes in yaml files
    watchSources := Def.uncached {
      watchSources.value ++
      mojozJobMetadataFolders.value.map(WatchSource(_)) ++
      mojozRouteMetadataFolders.value.map(WatchSource(_)) ++
      mojozTableMetadataFolders.value.map(WatchSource(_)) ++
      mojozViewMetadataFolders.value.map(WatchSource(_)) ++
      mojozAllSourceFiles.value.groupBy(_.getParentFile.getAbsolutePath).map {
        case (path, files) =>
          val names = files.map(_.getName).toSet
          WatchSource(new File(path), includeFilter = new SimpleFilter(names.contains), excludeFilter = NothingFilter)
      }
    }
  ) ++ inConfig(MojozMacroCompile)(Defaults.compileSettings ++ Seq(
    sources             := Def.uncached(mojozMacroSources.value),
    classDirectory      := (Compile / classDirectory).value,
    dependencyClasspath := Def.uncached((Compile / dependencyClasspath).value),
    sbtClassDirectory   := Def.uncached {
      val sbtScalaVer = appConfiguration.value.provider.scalaProvider.version()
      val sbtScalaBinVer = sbtScalaVer.split('.').take(2).mkString(".")
      baseDirectory.value / "project" / "target" / s"scala-$sbtScalaBinVer" / s"sbt-${sbtBinaryVersion.value}" / "classes"
    },
    mojozMacroCompile   := Def.uncached {
      // compile macro sources for tresql scala macro
      compile.value
      // compile macro sources for view compiler which runs no SBT's own scala
      val srcs      = sources.value
      val sbtClsDir = sbtClassDirectory.value
      val stampFile = sbtClsDir / ".mojoz-macro-compile-stamp"
      val needsCompile = srcs.nonEmpty && (
        !stampFile.exists() ||
        srcs.exists(_.lastModified() > stampFile.lastModified())
      )
      val log = streams.value.log // evaluate streams.value outside of if condition so it does not give warning
      if (needsCompile) {
        implicit val conv: xsbti.FileConverter = fileConverter.value
        val scalaProvider = appConfiguration.value.provider.scalaProvider
        val sbtDepClasspath = toAttributedFiles(MojozPlugin.buildClasspath)
        MojozPlugin.runScalaCompiler(
          srcs,
          sbtClsDir,
          sbtDepClasspath,
          scalaProvider.jars().toSeq,
          scalaProvider.version(),
          javaHome.value,
          log,
          conv,
        )
        IO.touch(stampFile)
      }
    },
  ))

  def runScalaCompiler(
    sources: Seq[File],
    destinationDirectory: File,
    classpath: Classpath,
    scalaJars: Seq[File],
    scalaVersion: String,
    javaHome: Option[File],
    log: sbt.util.Logger,
    fileConverter: xsbti.FileConverter,
  ): Unit = {
    if (sources.isEmpty) return
    destinationDirectory.mkdirs()
    val javaExe = javaHome
      .map(_ / "bin" / "java")
      .getOrElse(file(sys.props("java.home")) / "bin" / "java")
      .getAbsolutePath
    val compilerCp = scalaJars.map(_.getAbsolutePath).mkString(java.io.File.pathSeparator)
    implicit val conv: xsbti.FileConverter = fileConverter
    val projectCp  = toFiles(classpath).map(_.getAbsolutePath).mkString(java.io.File.pathSeparator)
    val cmd = Seq(
      javaExe,
      "-cp", compilerCp,
      "scala.tools.nsc.Main",
      "-classpath", projectCp,
      "-d", destinationDirectory.getAbsolutePath,
    ) ++ sources.map(_.getAbsolutePath)
    log.info(s"compiling ${sources.size} Scala source with Scala $scalaVersion to $destinationDirectory...")
    import scala.sys.process._
    val exitCode = Process(cmd) ! new ProcessLogger {
      override def out(s: => String): Unit = log.info(s)
      override def err(s: => String): Unit = log.error(s)
      override def buffer[T](f: => T): T = f
    }
    if (exitCode != 0) sys.error(s"Scala compilation failed with exit code $exitCode")
  }

  def buildClasspath: Seq[File] = {
    def urls(cl: ClassLoader): Seq[java.net.URL] = cl match {
      case null                           => Nil
      case urlCl: java.net.URLClassLoader => urlCl.getURLs.toSeq ++ urls(urlCl.getParent)
      case other                          => urls(other.getParent)
    }
    urls(getClass.getClassLoader).map(u => new File(u.toURI)).filter(_.exists)
  }

  def getMojozResourceClassLoader(files: Seq[File]): ClassLoader = {
    val urls = files.map(_.toURI.toURL).toArray
    new java.net.URLClassLoader(urls, getClass.getClassLoader)
  }
}
