language: scala
dist: xenial
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean scripted
scala:
  - 2.12.12
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk8
notifications:
  email:
    - guntiso@uniso.lv
    - martins@uniso.lv
