name: Build and test
on:   [push]
jobs:
  Build-and-test:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os:   [ubuntu-24.04]   # TODO macos-latest, windows-latest
        java: [17]
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v6
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: sbt
    - name: Set up sbt
      uses: sbt/setup-sbt@v1
    - name: Compile and test and check version policy
      run:  sbt "++2.12.21; clean; scripted; ++3.8.4; scripted; +versionPolicyCheck"
