name: Build and test
on:   [push]
jobs:
  Build-and-test:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os:   [ubuntu-22.04]   # TODO macos-latest, windows-latest
        java: [17]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Compile and test and check version policy
      run:  sbt "++2.12.21; clean; scripted; ++3.8.4; scripted; +versionPolicyCheck"
